version: "2.4"
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
    networks:
    - app-network
    volumes:
    - mysql_data:/var/lib/mysql
volumes:
  mysql_data: {}
networks:
  app-network:
    driver: bridge

