spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: 'jdbc:tc:mysql:5.6://hostname/databasename'
#    driver-class-name: org.h2.Driver
#    url: 'jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE'
#    username: "sa"
#    password: "sa"

